name: Coverage
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: x64
      - run: pip install nox==2020.8.22
      - run: pip install poetry==1.0.10
      - run: nox --session tests-3.8 coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
